name: growth_gauge
description: "An application to keep the count of the tasks or activities."
publish_to: 'none' 
version: 1.0.1+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  freezed_annotation: 2.4.4
  json_annotation: ^4.9.0
  uuid: ^4.5.1
  shared_preferences: ^2.5.2
  path_provider: ^2.1.5
  provider: ^6.1.2
  lottie: ^3.3.1
  intl: ^0.20.2
  fl_chart: 0.70.2
  file_picker: ^9.0.2
  flutter_heatmap_calendar: ^1.0.5
  logger: ^2.5.0
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3
  build_runner: ^2.4.15
  freezed: 2.5.8
  json_serializable: ^6.9.0
  import_sorter: 4.6.0

flutter:
  uses-material-design: true
  fonts:
    - family: Cera
      fonts:
        - asset: assets/fonts/CeraPro.ttf
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato.ttf
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat.ttf
    - family: OpenSans.ttf
      fonts:
        - asset: assets/fonts/OpenSans.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto.ttf
  assets:
    - assets/images/
    - assets/animations/

import_sorter:
  comments: false

