name: growth_gauge
version: 1.1.2+1
publish_to: none
environment:
  sdk: ">=3.4.1 <4.0.0"
description: An application to keep the count of the tasks or activities.
dependencies:
  collection: ^1.19.1
  csv: ^6.0.0
  cupertino_icons: ^1.0.6
  file_picker: ^9.2.1
  fl_chart: 0.68.0
  flutter:
    sdk: flutter
  flutter_heatmap_calendar: ^1.0.5
  flutter_local_notifications: ^19.1.0
  flutter_secure_storage: ^9.2.4
  flutter_timezone: ^4.1.0
  freezed_annotation: 2.4.4
  intl: ^0.20.2
  json_annotation: ^4.9.0
  local_auth: ^2.1.6
  lottie: ^3.3.1
  page_transition: ^2.2.1
  path_provider: ^2.1.5
  provider: ^6.1.4
  shared_preferences: ^2.5.3
  timezone: ^0.10.0
  uuid: ^4.5.1
dev_dependencies:
  build_runner: ^2.4.15
  flutter_launcher_icons: ^0.14.3
  flutter_test:
    sdk: flutter
  freezed: 2.5.8
  import_sorter: 4.6.0
  json_serializable: ^6.9.5
  lint: ^2.8.0
  msix: ^3.16.9
  pubspec_dependency_sorter: ^1.0.5
flutter:
  uses-material-design: true
  fonts:
    - family: Cera
      fonts:
        - asset: assets/fonts/CeraPro.ttf
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato.ttf
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat.ttf
    - family: OpenSans.ttf
      fonts:
        - asset: assets/fonts/OpenSans.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto.ttf
  assets:
    - assets/images/
    - assets/animations/
    - assets/sounds/
import_sorter:
  comments: false
msix_config:
  display_name: Growth Gauge
  identity_name: Com.GrowthGauge
  publisher: "CN=Unknown, O=Unknown, C=Unknown"
  languages: en-us
  logo_path: "assets/images/icon.png"
  start_menu_icon_path: "assets/images/icon.png"
  tile_icon_path: "assets/images/icon.png"
  store: false
  signtool_options: /q /fd sha256 /n "CN=Unknown, O=Unknown, C=Unknown" /tr http://timestamp.digicert.com
  #install_certificate: false
  output_name: GrowthGauge
  toast_activator:
    clsid: "9b17769e-c5cd-424a-b859-1e8b873909c1"
    arguments: "msix-args"
    display_name: "Growth Gauge"
