import 'package:flutter/material.dart';

enum AppThemeName {
  light,
  lightMediumContrast,
  lightHighContrast,
  dark,
  darkMediumContrast,
  darkHighContrast,
}

extension AppThemeNameExtension on AppThemeName {
  String getLabel() {
    switch (this) {
      case AppThemeName.light:
        return 'Light';
      case AppThemeName.lightMediumContrast:
        return 'Light Medium Contrast';
      case AppThemeName.lightHighContrast:
        return 'Light High Contrast';
      case AppThemeName.dark:
        return 'Dark';
      case AppThemeName.darkMediumContrast:
        return 'Dark Medium Contrast';
      case AppThemeName.darkHighContrast:
        return 'Dark High Contrast';
    }
  }
}

class AppColorTheme {
  final AppThemeName name;
  final ColorScheme colorScheme;

  const AppColorTheme({required this.name, required this.colorScheme});
}

List<AppColorTheme> appColorThemes = [
  const AppColorTheme(
    name: AppThemeName.light,
    colorScheme: ColorScheme(
      brightness: Brightness.light,
      primary: Color(0xff66558e),
      surfaceTint: Color(0xff66558e),
      onPrimary: Color(0xffffffff),
      primaryContainer: Color(0xffe9ddff),
      onPrimaryContainer: Color(0xff210f47),
      secondary: Color(0xff625b70),
      onSecondary: Color(0xffffffff),
      secondaryContainer: Color(0xffe9def8),
      onSecondaryContainer: Color(0xff1e192b),
      tertiary: Color(0xff7e525f),
      onTertiary: Color(0xffffffff),
      tertiaryContainer: Color(0xffffd9e2),
      onTertiaryContainer: Color(0xff31101c),
      error: Color(0xffba1a1a),
      onError: Color(0xffffffff),
      errorContainer: Color(0xffffdad6),
      onErrorContainer: Color(0xff410002),
      surface: Color(0xfffef7ff),
      onSurface: Color(0xff1d1b20),
      onSurfaceVariant: Color(0xff49454e),
      outline: Color(0xff7a757f),
      outlineVariant: Color(0xffcac4cf),
      shadow: Color(0xff000000),
      scrim: Color(0xff000000),
      inverseSurface: Color(0xff322f35),
      inversePrimary: Color(0xffd0bcfe),
      primaryFixed: Color(0xffe9ddff),
      onPrimaryFixed: Color(0xff210f47),
      primaryFixedDim: Color(0xffd0bcfe),
      onPrimaryFixedVariant: Color(0xff4e3d75),
      secondaryFixed: Color(0xffe9def8),
      onSecondaryFixed: Color(0xff1e192b),
      secondaryFixedDim: Color(0xffccc2db),
      onSecondaryFixedVariant: Color(0xff4a4458),
      tertiaryFixed: Color(0xffffd9e2),
      onTertiaryFixed: Color(0xff31101c),
      tertiaryFixedDim: Color(0xfff0b8c7),
      onTertiaryFixedVariant: Color(0xff633b47),
      surfaceDim: Color(0xffded8e0),
      surfaceBright: Color(0xfffef7ff),
      surfaceContainerLowest: Color(0xffffffff),
      surfaceContainerLow: Color(0xfff8f1fa),
      surfaceContainer: Color(0xfff2ecf4),
      surfaceContainerHigh: Color(0xffece6ee),
      surfaceContainerHighest: Color(0xffe6e0e8),
    ),
  ),
  const AppColorTheme(
    name: AppThemeName.lightMediumContrast,
    colorScheme: ColorScheme(
      brightness: Brightness.light,
      primary: Color(0xff4a3971),
      surfaceTint: Color(0xff66558e),
      onPrimary: Color(0xffffffff),
      primaryContainer: Color(0xff7d6ba6),
      onPrimaryContainer: Color(0xffffffff),
      secondary: Color(0xff464054),
      onSecondary: Color(0xffffffff),
      secondaryContainer: Color(0xff797187),
      onSecondaryContainer: Color(0xffffffff),
      tertiary: Color(0xff5f3744),
      onTertiary: Color(0xffffffff),
      tertiaryContainer: Color(0xff966775),
      onTertiaryContainer: Color(0xffffffff),
      error: Color(0xff8c0009),
      onError: Color(0xffffffff),
      errorContainer: Color(0xffda342e),
      onErrorContainer: Color(0xffffffff),
      surface: Color(0xfffef7ff),
      onSurface: Color(0xff1d1b20),
      onSurfaceVariant: Color(0xff45414a),
      outline: Color(0xff615d67),
      outlineVariant: Color(0xff7e7983),
      shadow: Color(0xff000000),
      scrim: Color(0xff000000),
      inverseSurface: Color(0xff322f35),
      inversePrimary: Color(0xffd0bcfe),
      primaryFixed: Color(0xff7d6ba6),
      onPrimaryFixed: Color(0xffffffff),
      primaryFixedDim: Color(0xff63528c),
      onPrimaryFixedVariant: Color(0xffffffff),
      secondaryFixed: Color(0xff797187),
      onSecondaryFixed: Color(0xffffffff),
      secondaryFixedDim: Color(0xff60596e),
      onSecondaryFixedVariant: Color(0xffffffff),
      tertiaryFixed: Color(0xff966775),
      onTertiaryFixed: Color(0xffffffff),
      tertiaryFixedDim: Color(0xff7b4f5d),
      onTertiaryFixedVariant: Color(0xffffffff),
      surfaceDim: Color(0xffded8e0),
      surfaceBright: Color(0xfffef7ff),
      surfaceContainerLowest: Color(0xffffffff),
      surfaceContainerLow: Color(0xfff8f1fa),
      surfaceContainer: Color(0xfff2ecf4),
      surfaceContainerHigh: Color(0xffece6ee),
      surfaceContainerHighest: Color(0xffe6e0e8),
    ),
  ),
  const AppColorTheme(
    name: AppThemeName.lightHighContrast,
    colorScheme: ColorScheme(
      brightness: Brightness.light,
      primary: Color(0xff28174e),
      surfaceTint: Color(0xff66558e),
      onPrimary: Color(0xffffffff),
      primaryContainer: Color(0xff4a3971),
      onPrimaryContainer: Color(0xffffffff),
      secondary: Color(0xff251f32),
      onSecondary: Color(0xffffffff),
      secondaryContainer: Color(0xff464054),
      onSecondaryContainer: Color(0xffffffff),
      tertiary: Color(0xff391723),
      onTertiary: Color(0xffffffff),
      tertiaryContainer: Color(0xff5f3744),
      onTertiaryContainer: Color(0xffffffff),
      error: Color(0xff4e0002),
      onError: Color(0xffffffff),
      errorContainer: Color(0xff8c0009),
      onErrorContainer: Color(0xffffffff),
      surface: Color(0xfffef7ff),
      onSurface: Color(0xff000000),
      onSurfaceVariant: Color(0xff25232b),
      outline: Color(0xff45414a),
      outlineVariant: Color(0xff45414a),
      shadow: Color(0xff000000),
      scrim: Color(0xff000000),
      inverseSurface: Color(0xff322f35),
      inversePrimary: Color(0xfff2e8ff),
      primaryFixed: Color(0xff4a3971),
      onPrimaryFixed: Color(0xffffffff),
      primaryFixedDim: Color(0xff332259),
      onPrimaryFixedVariant: Color(0xffffffff),
      secondaryFixed: Color(0xff464054),
      onSecondaryFixed: Color(0xffffffff),
      secondaryFixedDim: Color(0xff302a3d),
      onSecondaryFixedVariant: Color(0xffffffff),
      tertiaryFixed: Color(0xff5f3744),
      onTertiaryFixed: Color(0xffffffff),
      tertiaryFixedDim: Color(0xff46212d),
      onTertiaryFixedVariant: Color(0xffffffff),
      surfaceDim: Color(0xffded8e0),
      surfaceBright: Color(0xfffef7ff),
      surfaceContainerLowest: Color(0xffffffff),
      surfaceContainerLow: Color(0xfff8f1fa),
      surfaceContainer: Color(0xfff2ecf4),
      surfaceContainerHigh: Color(0xffece6ee),
      surfaceContainerHighest: Color(0xffe6e0e8),
    ),
  ),
  const AppColorTheme(
    name: AppThemeName.dark,
    colorScheme: ColorScheme(
      brightness: Brightness.dark,
      primary: Color(0xffd0bcfe),
      surfaceTint: Color(0xffd0bcfe),
      onPrimary: Color(0xff37265d),
      primaryContainer: Color(0xff4e3d75),
      onPrimaryContainer: Color(0xffe9ddff),
      secondary: Color(0xffccc2db),
      onSecondary: Color(0xff332d41),
      secondaryContainer: Color(0xff4a4458),
      onSecondaryContainer: Color(0xffe9def8),
      tertiary: Color(0xfff0b8c7),
      onTertiary: Color(0xff4a2531),
      tertiaryContainer: Color(0xff633b47),
      onTertiaryContainer: Color(0xffffd9e2),
      error: Color(0xffffb4ab),
      onError: Color(0xff690005),
      errorContainer: Color(0xff93000a),
      onErrorContainer: Color(0xffffdad6),
      surface: Color(0xff141218),
      onSurface: Color(0xffe6e0e8),
      onSurfaceVariant: Color(0xffcac4cf),
      outline: Color(0xff948f99),
      outlineVariant: Color(0xff49454e),
      shadow: Color(0xff000000),
      scrim: Color(0xff000000),
      inverseSurface: Color(0xffe6e0e8),
      inversePrimary: Color(0xff66558e),
      primaryFixed: Color(0xffe9ddff),
      onPrimaryFixed: Color(0xff210f47),
      primaryFixedDim: Color(0xffd0bcfe),
      onPrimaryFixedVariant: Color(0xff4e3d75),
      secondaryFixed: Color(0xffe9def8),
      onSecondaryFixed: Color(0xff1e192b),
      secondaryFixedDim: Color(0xffccc2db),
      onSecondaryFixedVariant: Color(0xff4a4458),
      tertiaryFixed: Color(0xffffd9e2),
      onTertiaryFixed: Color(0xff31101c),
      tertiaryFixedDim: Color(0xfff0b8c7),
      onTertiaryFixedVariant: Color(0xff633b47),
      surfaceDim: Color(0xff141218),
      surfaceBright: Color(0xff3b383e),
      surfaceContainerLowest: Color(0xff0f0d13),
      surfaceContainerLow: Color(0xff1d1b20),
      surfaceContainer: Color(0xff211f24),
      surfaceContainerHigh: Color(0xff2b292f),
      surfaceContainerHighest: Color(0xff36343a),
    ),
  ),
  const AppColorTheme(
    name: AppThemeName.darkMediumContrast,
    colorScheme: ColorScheme(
      brightness: Brightness.dark,
      primary: Color(0xffd4c1ff),
      surfaceTint: Color(0xffd0bcfe),
      onPrimary: Color(0xff1c0841),
      primaryContainer: Color(0xff9987c4),
      onPrimaryContainer: Color(0xff000000),
      secondary: Color(0xffd0c6e0),
      onSecondary: Color(0xff191325),
      secondaryContainer: Color(0xff958da4),
      onSecondaryContainer: Color(0xff000000),
      tertiary: Color(0xfff4bccb),
      onTertiary: Color(0xff2b0b17),
      tertiaryContainer: Color(0xffb58391),
      onTertiaryContainer: Color(0xff000000),
      error: Color(0xffffbab1),
      onError: Color(0xff370001),
      errorContainer: Color(0xffff5449),
      onErrorContainer: Color(0xff000000),
      surface: Color(0xff141218),
      onSurface: Color(0xfffff9ff),
      onSurfaceVariant: Color(0xffcfc8d3),
      outline: Color(0xffa6a1ab),
      outlineVariant: Color(0xff86818b),
      shadow: Color(0xff000000),
      scrim: Color(0xff000000),
      inverseSurface: Color(0xffe6e0e8),
      inversePrimary: Color(0xff4f3e76),
      primaryFixed: Color(0xffe9ddff),
      onPrimaryFixed: Color(0xff17033c),
      primaryFixedDim: Color(0xffd0bcfe),
      onPrimaryFixedVariant: Color(0xff3d2c63),
      secondaryFixed: Color(0xffe9def8),
      onSecondaryFixed: Color(0xff130e20),
      secondaryFixedDim: Color(0xffccc2db),
      onSecondaryFixedVariant: Color(0xff393347),
      tertiaryFixed: Color(0xffffd9e2),
      onTertiaryFixed: Color(0xff240612),
      tertiaryFixedDim: Color(0xfff0b8c7),
      onTertiaryFixedVariant: Color(0xff502b37),
      surfaceDim: Color(0xff141218),
      surfaceBright: Color(0xff3b383e),
      surfaceContainerLowest: Color(0xff0f0d13),
      surfaceContainerLow: Color(0xff1d1b20),
      surfaceContainer: Color(0xff211f24),
      surfaceContainerHigh: Color(0xff2b292f),
      surfaceContainerHighest: Color(0xff36343a),
    ),
  ),
  const AppColorTheme(
    name: AppThemeName.darkHighContrast,
    colorScheme: ColorScheme(
      brightness: Brightness.dark,
      primary: Color(0xfffff9ff),
      surfaceTint: Color(0xffd0bcfe),
      onPrimary: Color(0xff000000),
      primaryContainer: Color(0xffd4c1ff),
      onPrimaryContainer: Color(0xff000000),
      secondary: Color(0xfffff9ff),
      onSecondary: Color(0xff000000),
      secondaryContainer: Color(0xffd0c6e0),
      onSecondaryContainer: Color(0xff000000),
      tertiary: Color(0xfffff9f9),
      onTertiary: Color(0xff000000),
      tertiaryContainer: Color(0xfff4bccb),
      onTertiaryContainer: Color(0xff000000),
      error: Color(0xfffff9f9),
      onError: Color(0xff000000),
      errorContainer: Color(0xffffbab1),
      onErrorContainer: Color(0xff000000),
      surface: Color(0xff141218),
      onSurface: Color(0xffffffff),
      onSurfaceVariant: Color(0xfffff9ff),
      outline: Color(0xffcfc8d3),
      outlineVariant: Color(0xffcfc8d3),
      shadow: Color(0xff000000),
      scrim: Color(0xff000000),
      inverseSurface: Color(0xffe6e0e8),
      inversePrimary: Color(0xff301f56),
      primaryFixed: Color(0xffede2ff),
      onPrimaryFixed: Color(0xff000000),
      primaryFixedDim: Color(0xffd4c1ff),
      onPrimaryFixedVariant: Color(0xff1c0841),
      secondaryFixed: Color(0xffede2fc),
      onSecondaryFixed: Color(0xff000000),
      secondaryFixedDim: Color(0xffd0c6e0),
      onSecondaryFixedVariant: Color(0xff191325),
      tertiaryFixed: Color(0xffffdfe6),
      onTertiaryFixed: Color(0xff000000),
      tertiaryFixedDim: Color(0xfff4bccb),
      onTertiaryFixedVariant: Color(0xff2b0b17),
      surfaceDim: Color(0xff141218),
      surfaceBright: Color(0xff3b383e),
      surfaceContainerLowest: Color(0xff0f0d13),
      surfaceContainerLow: Color(0xff1d1b20),
      surfaceContainer: Color(0xff211f24),
      surfaceContainerHigh: Color(0xff2b292f),
      surfaceContainerHighest: Color(0xff36343a),
    ),
  ),
];
