// Mocks generated by Mockito 5.4.6 from annotations
// in growth_gauge/test/features/notification/notification_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flutter/material.dart' as _i5;
import 'package:growth_gauge/data/services/notification_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:timezone/timezone.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [NotificationServiceBase].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotificationServiceBase extends _i1.Mock
    implements _i2.NotificationServiceBase {
  MockNotificationServiceBase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> initializeTimeZone() => (super.noSuchMethod(
        Invocation.method(
          #initializeTimeZone,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> initializeNotificationSettings() => (super.noSuchMethod(
        Invocation.method(
          #initializeNotificationSettings,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> requestPlatformPermissions() => (super.noSuchMethod(
        Invocation.method(
          #requestPlatformPermissions,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> isAndroidPermissionGranted() => (super.noSuchMethod(
        Invocation.method(
          #isAndroidPermissionGranted,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> scheduleNotification({
    required int? id,
    required String? title,
    required String? body,
    required _i4.TZDateTime? scheduledTime,
    String? sound,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #scheduleNotification,
          [],
          {
            #id: id,
            #title: title,
            #body: body,
            #scheduledTime: scheduledTime,
            #sound: sound,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> scheduleDailyNotification({
    required int? id,
    required String? title,
    required String? body,
    required _i5.TimeOfDay? time,
    String? sound,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #scheduleDailyNotification,
          [],
          {
            #id: id,
            #title: title,
            #body: body,
            #time: time,
            #sound: sound,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
