name: Build and Release Linux

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter SDK
        uses: flutter-actions/setup-flutter@v4
        with:
          channel: stable
          version: 3.22.1
          cache: true
          cache-sdk: true

      - name: Get dependencies
        run: flutter pub get

      - name: Flutter Analyze
        run: flutter analyze

      - name: Install Linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build libgtk-3-dev libglib2.0-dev

      - name: Build Linux release
        run: flutter build linux --release

      - name: Zip Release
        run: |
          cd build/linux/x64/release/bundle
          zip -r ../../../../linux_release.zip .

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: linux_release.zip
          asset_name: growth_gauge_linux-${{ github.ref }}.zip
          asset_content_type: application/zip