name: Build and Release Windows

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter SDK
        uses: flutter-actions/setup-flutter@v4
        with:
          channel: stable
          version: 3.22.1

      - name: Get dependencies
        run: flutter pub get

      - name: Flutter Analyze
        run: flutter analyze

      - name: Build Windows release
        run: flutter build windows --release

      - name: Zip Release
        run: |
          Compress-Archive -Path build\windows\runner\Release\* -DestinationPath growth_gauge.zip

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: growth_gauge.zip
          asset_name: ${{ github.event.release.tag_name }}.zip
          asset_content_type: application/zip